FROM minio/mc

ENV SOURCE_ACCESS_KEY=$SOURCE_ACCESS_KEY 

ENV SOURCE_SECRET_KEY=$SOURCE_SECRET_KEY

ENV DESTINATION_ACCESS_KEY=$DESTINATION_ACCESS_KEY

ENV DESTINATION_SECRET_KEY=$DESTINATION_SECRET_KEY

ENV DESTINATION_BUCKET=$DESTINATION_BUCKET

ENV SOURCE_BUCKET=$SOURCE_BUCKET

ENV SOURCE_REGION=$SOURCE_REGION

ENV DESTINATION_REGION=$DESTINATION_REGION

COPY docker-entrypoint.sh /usr/local/bin

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]